### ISSUE TITLE
how can use it in java?can you build an exe for cmd use?

### ISSUE THREAD

**Issue by qq1053831109** [VADIMREX/JassToTs#1]
how can use it in java?can you build an exe for cmd use?

**Comment by VADIMREX** [comment]
Hello @qq1053831109!
I've builded today binaries. You can use it with dotnet core runtime, like:
```powershell
dotnet .\JassToTs.dll -h
```
For .exe I need to upgrade project framework version. I'll try to do it in the next weekend (saturday-sunday).

**Comment by qq1053831109** [comment]
Thank you very much. exe with cmd use will use in every programmer

**Comment by VADIMREX** [comment]
Hello @qq1053831109!
I've switched .net version and bulded project into .exe.
[Pre-release 0.4](https://github.com/VADIMREX/JassToTs/releases/tag/0.4)
