### ISSUE TITLE
ydwe compatible More information

### ISSUE THREAD

**Issue by qq1053831109** [VADIMREX/JassToTs#11]
YDLocal[x]Set or get have YDLocalSet YDLocalGet !
no [x]

**Comment by qq1053831109** [comment]
`function Trig_nandu_dialog_initFunc009Conditions takes nothing returns nothing
    call YDLocalSet(GetTriggeringTrigger(), integer, "int", YDUserDataGet(button, GetClickedButtonBJ(), "nandu", integer))
    call YDWESaveIntegerByString( "system", "nandu", YDLocalGet(GetTriggeringTrigger(), integer, "int") )
    call YDWESaveStringByString( "system", "nandu_str", I2S(YDLocalGet(GetTriggeringTrigger(), integer, "int")) )
    if ((YDLocalGet(GetTriggeringTrigger(), integer, "int") == 666666)) then
        call YDWESaveStringByString( "system", "nandu_str", "无尽" )
        call AddPlayerTechResearched( Player(11), 'qzk1', 16 )
    else
    endif
    if ((YDLocalGet(GetTriggeringTrigger(), integer, "int") == 7777777)) then
        call YDWESaveStringByString( "system", "nandu_str", "挂机" )
    else
    endif
    if ((YDLocalGet(GetTriggeringTrigger(), integer, "int") < 10)) then
        call DisplayTimedTextToForce( GetPlayersAll(), 15.00, YDWEOperatorString3("|CFFFF0000选择的难度 ： 难度", I2S(YDLocalGet(GetTriggeringTrigger(), integer, "int")), "") )
        call YDLocalSet(GetTriggeringTrigger(), integer, "int", ( YDLocalGet(GetTriggeringTrigger(), integer, "int") - 1 ))
        call YDLocalSet(GetTriggeringTrigger(), integer, "int", ( YDLocalGet(GetTriggeringTrigger(), integer, "int") * YDLocalGet(GetTriggeringTrigger(), integer, "int") ))
        call AddPlayerTechResearched( Player(11), 'qzk1', YDLocalGet(GetTriggeringTrigger(), integer, "int") )
    else
    endif
    call YDLocal4Release()
    call DestroyTrigger(GetTriggeringTrigger())
endfunction

function Trig_nandu_dialog_initActions takes nothing returns nothing
    local trigger ydl_trigger
    YDLocalInitialize()
    call YDLocal1Set(dialog, "dialog", DialogCreate())
    call DialogSetMessage( YDLocal1Get(dialog, "dialog"), "TRIGSTR_048" )
    set bj_forLoopAIndex = 1
    set bj_forLoopAIndexEnd = 9
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        call DialogAddButtonBJ( YDLocal1Get(dialog, "dialog"), YDWEOperatorString3("难度", I2S(bj_forLoopAIndex), "") )
        call YDUserDataSet(button, bj_lastCreatedButton, "nandu", integer, bj_forLoopAIndex)
        set bj_forLoopAIndex = bj_forLoopAIndex + 1
    endloop
    call DialogAddButtonBJ( YDLocal1Get(dialog, "dialog"), "TRIGSTR_049" )
    call YDUserDataSet(button, bj_lastCreatedButton, "nandu", integer, 666666)
    call DialogDisplay( Player(0), YDLocal1Get(dialog, "dialog"), true )
    // onclick
    set ydl_trigger = CreateTrigger()
    call YDLocalSet(ydl_trigger, integer, "int", YDLocal1Get(integer, "int"))
    call TriggerRegisterDialogEvent( ydl_trigger, YDLocal1Get(dialog, "dialog") )
    call TriggerAddCondition(ydl_trigger, Condition(function Trig_nandu_dialog_initFunc009Conditions))
    call YDLocal1Release()
    set ydl_trigger = null
endfunction

//===========================================================================
function InitTrig_nandu_dialog_init takes nothing returns nothing
    set gg_trg_nandu_dialog_init = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_nandu_dialog_init, "nandu_dialog_init")
#endif
    call TriggerRegisterTimerEventSingle( gg_trg_nandu_dialog_init, 0.50 )
    call TriggerAddAction(gg_trg_nandu_dialog_init, function Trig_nandu_dialog_initActions)
endfunction

`

**Comment by VADIMREX** [comment]
In last commit added conversion of YDLocalSet and YDLocalGet. But what I need to do with first argument?

**Comment by qq1053831109** [comment]
Ignore the first parameter.

**Comment by VADIMREX** [comment]
In the last commit i ignored the first parameter.
