### ISSUE TITLE
code optimization

### ISSUE THREAD

**Issue by qq1053831109** [VADIMREX/JassToTs#4]
if ((DzAPI_Map_HasMallItem(YDLocal2Get(player, "wj"), "ZY100") == true)) then
        call YDUserDataSet(player, YDLocal2Get(player, "wj"), "swe_add_gold", integer, 105)
    else
    endif

can you convert to only have if! the else is empty.the jass code is by gui  convert jass

**Comment by VADIMREX** [comment]
I'll try to add simple optimizer

**Comment by qq1053831109** [comment]
and
 if (( codes )) 
convert to
 if ( codes )

**Comment by qq1053831109** [comment]
i make a gui for this. in china .  the gui is:
![image](https://user-images.githubusercontent.com/17372170/132112316-d025d1a7-0964-4580-9d70-cc8f4c6ac9a3.png)

**Comment by VADIMREX** [comment]
In new release added new flag -op for optimizations. Now it has optimization for empty else block and newsting brackets.
