### ISSUE TITLE
require fix

### ISSUE THREAD

**Issue by qq1053831109** [VADIMREX/JassToTs#5]
i need told every user to download .net5.0? and Teach them how can dowload that and install that. it not good for user.
![QQ图片20210908180324](https://user-images.githubusercontent.com/17372170/132490013-1e54530c-1561-49cd-a0e7-4da1862fe6ad.png)

**Comment by VADIMREX** [comment]
I'll look for standalone assembly.

**Comment by VADIMREX** [comment]
Hello @qq1053831109!
There is three ways to fix the problem:
1.  Build self-contained release:
    - pros: user not needed to install .net 5 runtime
    - cons: build size about ~50 MB (zipped ~25 MB)
2.  Migrate to java version:
    - pros: as user already downloaded java runtime, I can build simple .jar file
    - cons: java version is in progress
3.  With intaller provide to user .net 5 runtime redistributable
    - pros: nothing to do)
    - cons: not user friendly

So far, I have released the first option.
Please check pre-release 0.6

**Comment by qq1053831109** [comment]
i like 2. because my editor is java

**Comment by VADIMREX** [comment]
Builded java release into jar. Command line flags is same as in C# release. Here example:
```powershell
java -jar .\JassToTs.jar -h
```
