### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qq1053831109** [VADIMREX/JassToTs#6]
```
function a takes nothing returns nothing
  	local real b =-1
endfunction
```
cant work with "=-"

lexeing
Unhandled exception. System.Exception: Line 1, Col 20: wrong operator
   at Jass.JassLexer.TryParseOperator()
   at Jass.JassLexer.Tokenize(String source)
   at JassToTs.Program.TranslateFile(String ipath, String opath, String tpath)
   at JassToTs.Program.Main(String[] args)

**Comment by qq1053831109** [comment]
bug2: wrong globals declaration: new line expected
too strict

**Comment by qq1053831109** [comment]
bug2: wrong globals declaration: new line expected
too strict

**Comment by VADIMREX** [comment]
> ```
> function a takes nothing returns nothing
>   	local real b =-1
> endfunction
> ```
> 
> cant work with "=-"
> 
> lexeing
> Unhandled exception. System.Exception: Line 1, Col 20: wrong operator
> at Jass.JassLexer.TryParseOperator()
> at Jass.JassLexer.Tokenize(String source)
> at JassToTs.Program.TranslateFile(String ipath, String opath, String tpath)
> at JassToTs.Program.Main(String[] args)

I'll fix this.

**Comment by VADIMREX** [comment]
> bug2: wrong globals declaration: new line expected
> too strict

Please provide example. I'll fix.

**Comment by VADIMREX** [comment]
Fixed in new release!
