### ISSUE TITLE
 no Blanks may cause errors.

### ISSUE THREAD

**Issue by qq1053831109** [VADIMREX/JassToTs#7]
str = str.replace("=-", "= -");// set a=-1
        str = str.replace(">-", "> -");// if a>-1
        str = str.replace("<-", "< -");
        str = str.replace("endglobals", "endglobals\n\n");

maybe u can check this!

**Comment by VADIMREX** [comment]
It's already do this. Here example with all three cases:
```jass
function a takes nothing returns nothing
  	local real b=-1
    if b>-1 or b<-1 then
      set b=-2
    endif
endfunction
```
It translates into this:
```typescript
/// Some references
/// <reference path="war3core.d.ts"/>

function a (): void {
// local variables
    let b: number = - 1;
// function body
    if (b > - 1 || b < - 1)
        b = - 2;
}
```
Can you provide example?

**Comment by VADIMREX** [comment]
Added blanks in arguments of YDUserDataGet/YDUserDataSet macro for comma.
